### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tmillr**
improve wording/grammar in a couple places

### CODE REVIEW

**Comment by mbbill** [comment]
This is awesome. I'm not a native English speaker so I totally expect this many wording/spelling errors. Thanks!

**Comment by mbbill** [comment]
Please feel free to merge the PR when it's ready. Thanks again!

**Comment by tmillr** [comment]
@mbbill Of course!

I don't have write access to this repo so I can't merge my fork into your repo, but I will let you know when it is ready to merge and we'll go from there. Thanks for making this awesome plugin by the way!

**Comment by tmillr** [comment]
> Maybe we can merge the finished part. Thanks for the awesome work!

Awesome! Thank you so much for the merge and kind words!

I may make another pr soon and try to go over everything again...and this time try to do a bit better with my time management and everything lol. Sorry about that!

**Pull request merged**
